version: '3'
services:
  contatos:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: amazoncorretto
    container_name: contatoapp
    ports:
      - "80:8080"
    networks:
      - prodnet
    depends_on: 
      - "mongodb"
  mongodb:
    image: mongo
    networks:
      - prodnet
networks:
  prodnet:
    driver: bridge